### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by YouGina** [ameenmaali/qsfuzz#4]
I get the following error when I run a list of URL's:

```
goroutine 1 [running]:
main.getInjectedUrls(0xc4208f4280, 0xc42008e180, 0x51, 0xc420120e40, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/ameenmaali/qsfuzz/utils.go:191 +0xeb9
main.main()
        /go/src/github.com/ameenmaali/qsfuzz/main.go:151 +0x4e9
```

**Comment by ameenmaali** [comment]
Hey @YouGina thanks for sending that over. Can you please pull a new version and retry? I fixed a bug yesterday with this and you may have a previous version. Thanks!

**Comment by ShlomieLiberow** [comment]
I am still seeing it with the updated binary. Let me know how I can help with debugging

**Comment by ameenmaali** [comment]
@ShlomieLiberow, if you can provide problem URLs or the wordlist you are using that would be greatly appreciated (I know this may not be possible if the target is private, however). Unfortunately I am not able to reproduce as of now. Also, if you can provide your exact error message, that'd be helpful as the lines failed from @YouGina post match with the previous bug and in the current version would not make sense as it's on a curly bracket :)

**Comment by YouGina** [comment]
Yes, for me it seems fixed after updating.

**Comment by ameenmaali** [comment]
Closing as it appears to be fixed. If you still experience the error, please let me know!

**Comment by ShlomieLiberow** [comment]
Was not able to repo as my data was a live steam but seems to be OK now. Cheers!
